# Generated by Django 3.1.7 on 2022-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopaani',
            name='lookupkey',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
